### ISSUE TITLE
Error with renchan calculation

### ISSUE THREAD

**Issue by ishanpm** [saki-rinshan/RiichiMahjongCalculatorWeb#1]
When calculating non-dealer ron payments with renchan, it will instead display the value for a dealer ron. Looks like a copy/paste error here:

https://github.com/saki-rinshan/RiichiMahjongCalculatorWeb/blob/481c358931b17bddb3dbe3890c4db3e22d87fd5f/src/app/models/payout.ts#L136

**Comment by nith822** [comment]
Wow, nice catch! This does appear to be the issue; I'll fix it within the week.

**Comment by nith822** [comment]
Fixed with: https://github.com/saki-rinshan/RiichiMahjongCalculatorWeb/commit/d7b5a768ff2c01400363d32e9be03244f95d289f
